---
- hosts: localhost
  connection: local
  tasks:

      # Create a new instance
      - name: Launch a new instance
        ec2:
            key_name: first
            instance_type: t2.micro
            image: ami-0aa2b7722dc1b5612
            instance_ids: i-0abc1234567890def
            region: us-east-1
            group_id: sg-0f0f3ea42350f1639
            count: 1
            vpc_subnet_id: subnet-0bb711975146a3685
            wait: yes
            wait_timeout: 500
            instance_tags:
                Name: webserver1
        register: ec2
      # Print instance Details
      - name: Print Instance Details
        debug:
            var: ec2.instances[0].id

      - debug:
            var: ec2.region

      # Save instance details
      - name: Save instance details
        set_fact:
            instance_id: "{{ ec2.instances[0].id }}"
            region: "{{ ec2.region }}"



      # Wait for instance to boot up
      - name: Wait for Instance to boot
        wait_for:
            host: "{{ ec2.instances[0].public_ip }}"
            port: 22
            delay: 10
            timeout: 320
            become: yes
            become_user: ec2-user

      # Install nginx on ubuntu instance
      - name: Install Nginx
        become: yes
        become_user: ec2-user
        delegate_to: "{{ ec2.instances[0].public_ip }}"
        apt:
            update_cache: yes

      - name: Install Nginx
        become: yes
        become_user: ec2-user
        delegate_to: "{{ ec2.instances[0].public_ip }}"
        apt:
            name: nginx
            state: latest

      - name: Modify nginx index.html file
        become: yes
        become_user: ec2-user
        delegate_to: "{{ ec2.instances[0].public_ip }}"
        replace:
            path: /usr/share/nginx/html/index.html
            regexp: "<h1>Welcome to nginx!</h1>"
            replace: "<h1>Congratulations! AWS Virtual Machine is up and running</h1>"

      - name: Restart Nginx
        become: yes
        become_user: ec2-user
        delegate_to: "{{ ec2.instances[0].public_ip }}"
        service:
            name: nginx
            state: restarted
